### ISSUE TITLE
Drift not working on iOS Safari.

### ISSUE THREAD

**Issue by dave-cross** [negativetwelve/gatsby-plugin-drift#1]
I get this error when trying to use the drift plugin on iOS (tried on multiple devices, same error).

```
Blocked a frame with origin <My Website> from accessing a frame with origin "https://js.driftt.com". Protocols, domains, and ports must match.
```

It seems there's a Same-origin policy in play for mobile. Any advice on whether this is in the plugin code or purely on Drift's side?

**Update:** It also locks scroll on iOS devices. Inline styles are being added to HTML to prevent scroll, but because of the policy taking effect, there's no way to release the scroll lock without refreshing.

**Comment by negativetwelve** [comment]
Hi @cloudsociety, I think you should raise this issue with the official Drift support channel. This plugin just adds the script for loading Drift. From there, the normal bootstrapping process takes over.

**Comment by dave-cross** [comment]
That's what I thought, but wanted to be sure.

No worries. Will do. Thanks.
